### PR TITLE
/doom misc. edition

### PR DESCRIPTION
**Pull request by adroition**

### CODE REVIEW

**Comment by rovertdude** [comment]
As I said before - you need an approved issue for this.

**Comment by FriedChckn** [comment]
Clarify @rovertdude what needs to be done

**Comment by rovertdude** [comment]
#8 - it seems like a interesting possible addition.

**Comment by adroition** [comment]
I can change it to simply be suspending them.

**Comment by FriedChckn** [comment]
This is for wolfcraft not PugFreedom

**Comment by adroition** [comment]
Small change changing the wording to "wolves" instead of pugs - if needed, I can simply remove that line.

**Comment by rovertdude** [comment]
I think it is best to simply remove that line.

**Comment by FriedChckn** [comment]
Please do so

**Comment by adroition** [comment]
It's changed to fit that.

**Comment by rovertdude** [comment]
Alright - thanks for the PR!
The message fits what it does quite well.

**Comment by adroition** [comment]
Don't merge yet

**Comment by adroition** [comment]
there, just added /suspend as an alias

**Comment by FriedChckn** [comment]
I approve.

**Comment by rovertdude** [comment]
Thanks for the addition!

**Pull request merged**
