### PR TITLE
Req. Perms

### PR DESCRIPTION
**Pull request by PuggyCrew**
This is a misc. addition - awaiting to see if this can work out well.

### CODE REVIEW

**Comment by rovertdude** [comment]
How exactly does this help us?
"SERVER" is fine itself.

**Comment by PuggyCrew** [comment]
Sorry for the delay.
It can help due to the fact that /say is often abused - this can enforce it slightly.

**Comment by rovertdude** [comment]
Interesting idea.
However - more of enforcing would have to do with @FriedChckn as one of the owners of WolfCraft - I have no clue how to contact Wolfie.

**Comment by FriedChckn** [comment]
Looks good! All fine by me

**Comment by FriedChckn** [comment]
I have control over the developing side of the server, no need to contact wolfie

**Pull request merged**
