### PR TITLE
Misc. Changes

### PR DESCRIPTION
**Pull request by adroition**

### CODE REVIEW

**Comment by rovertdude** [comment]
There is no issue that is resolved with this.
This is locked until a issue is accepted under this.

**Comment by rovertdude** [comment]
Ready to merge when WFC 1.1 is ready for merges

**Comment by rovertdude** [comment]
Awaiting your approval to merge @adroition

**Comment by adroition** [comment]
Approved for merge, no bugs found.

**Comment by rovertdude** [comment]
Thanks for the changes!

**Pull request merged**
