### PR TITLE
/cake

### PR DESCRIPTION
**Pull request by adroition**
Minor /cake change.

### CODE REVIEW

**Comment by rovertdude** [comment]
Interesting idea.

**Comment by xOverloaded** [comment]
I dont like this, if you change the name of the achievement, change the name of the cake

**Comment by rovertdude** [comment]
@xOverloaded He removed it giving the achievement entirely.
This can resolve spam if achievements were enabled.

**Comment by xOverloaded** [comment]
Waiting for more input from @rovertdude

**Comment by adroition** [comment]
What needs changing?

**Comment by xOverloaded** [comment]
Oh, whoops, completely missed the red part, my bad

**Comment by rovertdude** [comment]
Nothing needs changing then?

**Comment by xOverloaded** [comment]
You have my approval to merge

**Comment by rovertdude** [comment]
merge early?
WFC 1.2 is not accepting yet but it can still be merged early

**Comment by xOverloaded** [comment]
No, but the changes I made to gtfo and saconfig, will they be lost?

**Comment by rovertdude** [comment]
No.

**Comment by xOverloaded** [comment]
Alright, we are all good here, merge whenever WFC 1.2 is ready

**Pull request merged**
